import pytest

from src.carousel_caption import format_carousel_caption, format_featured_works


def _artwork(number, *, title=None, artist=None, date=None, museum=None):
    return {
        "id": f"featured_{number}",
        "title": title or f"Title {number}",
        "artist": artist or f"Artist {number}",
        "date": date or f"Date {number}",
        "museum": museum or f"Museum {number}",
    }


def test_featured_works_preserves_selected_order_and_metadata_including_museum():
    selected_artworks = [
        _artwork(2, title="  Uncertain Title  ", artist="Attributed to Artist", date="c. 1900?"),
        _artwork(1, title="Unknown", artist="Artist unknown", date="Date unknown"),
    ]

    assert format_featured_works(selected_artworks) == (
        "1.   Uncertain Title   — Attributed to Artist, c. 1900?\n"
        "   Museum 2\n"
        "2. Unknown — Artist unknown, Date unknown\n"
        "   Museum 1"
    )


def test_gemini_editorial_prose_cannot_replace_the_deterministic_featured_works_list():
    selected_artworks = [_artwork(1), _artwork(2)]
    gemini_output = {
        "editorial_intro": "A focused introduction generated by Gemini.",
        "featured_works": "1. Invented Work — Invented Artist, Invented Date\n   Invented Museum",
    }
    caption = format_carousel_caption(
        theme_title="Selected Theme",
        editorial_intro=gemini_output["editorial_intro"],
        hashtags="#Art #MuseumArt #Painting #CuratedArt",
        featured_artworks=selected_artworks,
    )

    assert "Featured Works\n\n1. Title 1 — Artist 1, Date 1\n   Museum 1" in caption
    assert "2. Title 2 — Artist 2, Date 2\n   Museum 2" in caption
    assert gemini_output["featured_works"] not in caption


def test_non_featured_cover_metadata_cannot_enter_featured_works():
    selected_artworks = [_artwork(1), _artwork(2)]
    future_cover = _artwork(99, title="Cover Only", artist="Cover Artist", museum="Cover Museum")

    caption = format_carousel_caption(
        theme_title="Selected Theme",
        editorial_intro="A focused introduction generated by Gemini.",
        hashtags="#Art #MuseumArt #Painting #CuratedArt",
        featured_artworks=selected_artworks,
    )

    assert future_cover["title"] not in caption
    assert future_cover["artist"] not in caption
    assert future_cover["museum"] not in caption


@pytest.mark.parametrize("featured_count", [3, 4, 5, 8])
def test_adaptive_featured_works_numbering_matches_exact_final_order(featured_count):
    artworks = [_artwork(index) for index in range(1, featured_count + 1)]
    cover = _artwork(99, title="Cover Only")

    caption = format_carousel_caption(
        theme_title="Adaptive Theme",
        editorial_intro="A grounded introduction.",
        hashtags="#Art",
        featured_artworks=artworks,
    )

    assert [line.split(".", 1)[0] for line in caption.splitlines() if line[:1].isdigit()] == [
        str(index) for index in range(1, featured_count + 1)
    ]
    assert f"{featured_count + 1}." not in caption
    assert cover["title"] not in caption
